### ISSUE TITLE
Build fails with RN v0.45.1

### ISSUE THREAD

**Issue by asterikx** [anhtuank7c/maps-example#1]
Hi,

first of all thanks for your very good tutorial!

When cloning your repo and running `yarn install && react-native run-ios` everything works out-of-the box (with the correct Google Api Key given).

However, after upgrading React Native to the latest version 0.45.1 using `react-native-git-upgrade` `react-native run-ios` fails with the following error message:
```
** BUILD FAILED **


The following build commands failed:

	CompileC /Users/erikmuller/Downloads/maps-example-master/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/JSCSamplingProfiler.o /Users/erikmuller/Downloads/maps-example-master/node_modules/react-native/React/Modules/JSCSamplingProfiler.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

Have you any idea what this error is about? It would be really nice if your tutorial would work with the latest version of React Native as this is what most people are interested in, I guess 🙂 

I would contribute If I could, but for the moment I'm really stuck with that error 😞

**Comment by anhtuank7c** [comment]
This repo cannot be run on iOS because of Git Large File, i cannot push file greater than 50Mb.
So, please follow tutorial and make your own repo instead of clone and running this project.
