### ISSUE TITLE
Error: AirGoogleMaps dir must be added to your xCode project

### ISSUE THREAD

**Issue by benjamin3991** [anhtuank7c/maps-example#2]
Need Help:

For a new project I am able to get Google Maps for iOS, but when configuring for the existing project, It's still showing "console.error: "react-native-maps" AirGoogleMaps dir must be added to your xCode project"
Tried each and everything mentioned in " @[https://gist.github.com/heron2014/e60fa003e9b117ce80d56bb1d5bfe9e0](https://gist.github.com/heron2014/e60fa003e9b117ce80d56bb1d5bfe9e0)" as well as in your video.

Please refer screenshot:

<img width="378" alt="screen shot 2017-07-14 at 9 56 47 pm" src="https://user-images.githubusercontent.com/28919343/28248619-24f4ddbe-6a65-11e7-9618-ee4ae6c35815.png">

**Comment by anhtuank7c** [comment]
@benjamin3991 I did not try on RN 0.45.x.
Will do it soon.

**Comment by anhtuank7c** [comment]
I did try with `React Native 0.47.1` and they still work well.
I updated `README`.
Please try again ;)

**Comment by benjamin3991** [comment]
tried with React Native 0.48.4 recently. Still not working. Same issue.

**Comment by anhtuank7c** [comment]
I did not try with RN 48.4
