### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by dniccum** [anhtuank7c/maps-example#3]
Thank you for putting this together. I have followed your tutorial to a "T," however I am getting a consistent error on an iOS build

```
ld: file too small (length=0) file '/App/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/GoogleMaps' for architecture x86_64
```

I am using React Native `0.47.1` and Maps `0.16.3`. It appears that there is something wrong with the CocoaPods but I am not sure.

**Comment by anhtuank7c** [comment]
Please `cd` to your `ios` folder and remove `Podfile.lock` `Pods` folder and run `pod update` first.
We have to make sure got a latest cocoapods library.

**Comment by dniccum** [comment]
Yep I can confirm that I using the latest library.

**Comment by anhtuank7c** [comment]
@dniccum Can you give me a teamviewer ID, pass?
I can help you a bit.
