### ISSUE TITLE
Build fails with RN 0.48.3

### ISSUE THREAD

**Issue by pierreis** [anhtuank7c/maps-example#4]
Cross-ref: https://github.com/airbnb/react-native-maps/issues/1638

**Comment by anhtuank7c** [comment]
I did not try to integrate with RN 48.3
Will do it later

**Comment by anhtuank7c** [comment]
Please try new guide.
Remember to update your pod repo before do pod install.
https://github.com/anhtuank7c/maps-example/blob/master/README.md

**Comment by anhtuank7c** [comment]
I confirm that maps work well on RN 49.3

**Comment by urska19** [comment]
I can also confirm that it works with: `"react-native": "^0.49.3"` and  `"react-native-maps": "^0.17.1"`. Thanks @anhtuank7c for the guide. :)

**Comment by anhtuank7c** [comment]
@urska19 You're welcome
